version: '3.9'

services:
  cms-etl-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-etl-pipeline

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    volumes:
      # CHANGE THIS LINE
      - ./app/cms-pipeline-16bfeddf7657.json:/app/gcp-credentials.json:ro

      - ./data:/app/data
      - ./logs:/app/logs

    networks:
      - cms-network

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cms-network:
    driver: bridge



